spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/fs

    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
   # show-sql:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1090877835458-4dh79o676oabnfv3enn4be9hn5js1uq8.apps.googleusercontent.com
            client-secret: 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

  profiles:
    include: oauth



logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace



server:
  error:
    whitelabel:
      enabled: false


  servlet:
    session:
      timeout: 1800






